#pragma config(Sensor, in2,    ClawPot,        sensorPotentiometer)
#pragma config(Sensor, in3,    Gyro,           sensorGyro)
#pragma config(Sensor, in4,    ArmPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  bumper,         sensorTouch)
#pragma config(Sensor, dgtl2,  backrightIME,   sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  backleftIME,    sensorQuadEncoder)
#pragma config(Motor,  port2,           leftarm,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontleftdrive, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           middleleftdrive, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           backleftdrive, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           rightdrive,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightmiddledrive, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightarm,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

int activate = false;

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
  SensorValue[Gyro] = 0;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
void turnleft(int degrees10)
{
	SensorValue[Gyro] = 0;
	int error = 5;

	//While the absolute value of the gyro is less than the desired rotation - 100...
	while(abs(SensorValue[in3]) < degrees10 - 100)
	{
		motor[rightdrive] = motor[rightmiddledrive] = -75;
		motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = 75;
	}
	//Brief brake to eliminate some drift
	motor[rightdrive] = motor[rightmiddledrive] = 5;
	motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = -5;
	wait1Msec(100);

	//Second while loop to move the robot more slowly to its goal, also setting up a range
	//for the amount of acceptable error in the system
	while(abs(SensorValue[in3]) > degrees10 + error || abs(SensorValue[in3]) < degrees10 - error)
	{
		if(abs(SensorValue[in3]) > degrees10)
		{
			motor[rightdrive] = motor[rightmiddledrive] = 30;
			motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = -30;
		}
		else
		{
			motor[rightdrive] = motor[rightmiddledrive] = -30;
			motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = 30;
		}
	}
	//Stop
	motor[rightdrive] = motor[rightmiddledrive] = 0;
	motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = 0;
	wait1Msec(250);
}

void turnright(int degrees10)
{
	SensorValue[Gyro] = 0;
	int error = 5;

	//While the absolute value of the gyro is less than the desired rotation - 100...
	while(abs(SensorValue[in3]) < degrees10 - 100)
	{
		motor[rightdrive] = motor[rightmiddledrive] = 75;
		motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = -75;
	}
	//Brief brake to eliminate some drift
	motor[rightdrive] = motor[rightmiddledrive] = -5;
	motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = 5;
	wait1Msec(100);

	//Second while loop to move the robot more slowly to its goal, also setting up a range
	//for the amount of acceptable error in the system
	while(abs(SensorValue[in3]) > degrees10 + error || abs(SensorValue[in3]) < degrees10 - error)
	{
		if(abs(SensorValue[in3]) > degrees10)
		{
			motor[rightdrive] = motor[rightmiddledrive] = -30;
			motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = 30;
		}
		else
		{
			motor[rightdrive] = motor[rightmiddledrive] = 30;
			motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = -30;
		}
	}
	//Stop
	motor[rightdrive] = motor[rightmiddledrive] = 0;
	motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = 0;
	wait1Msec(250);
}

void moveforward(int degrees)
{
	SensorValue[backleftIME] = 0;
	SensorValue[backrightIME] = 0;
	while(SensorValue[backleftIME] < degrees)
	{
		motor[rightdrive] = motor[rightmiddledrive] = motor[frontleftdrive] = motor[middleleftdrive] = motor[backleftdrive] = 127;
	}
	motor[rightdrive] = motor[rightmiddledrive] = motor[frontleftdrive] = motor[middleleftdrive] = motor[backleftdrive] = 0;
	wait1Msec(100);
}

void movebackward(int degrees)
{
	SensorValue[backleftIME] = 0;
	SensorValue[backrightIME] = 0;
	while(SensorValue[backleftIME] > degrees)
	{
		motor[rightdrive] = motor[rightmiddledrive] = motor[frontleftdrive] = motor[middleleftdrive] = motor[backleftdrive] = -75;
	}
	motor[rightdrive] = motor[rightmiddledrive] = motor[frontleftdrive] = motor[middleleftdrive] = motor[backleftdrive] = 0;
	wait1Msec(100);
}

void raisearm(int degrees)
{
	while(SensorValue[ArmPot] > degrees)
	{
		motor[rightarm] = motor[leftarm] = 40;
	}
	motor[leftarm] = motor[rightarm] = -20;
}

void lowerarm(int degrees)
{
	while(SensorValue[ArmPot] < degrees)
	{
		motor[leftarm] = motor[rightarm] = -70;
	}
	motor[leftarm] = motor[rightarm] = 0;
}

void lowerarmtobottom()
{
	while(SensorValue[bumper] == 0)
	{
		motor[leftarm] = motor[rightarm] = -127;
	}
	motor[leftarm] = motor[rightarm] = -20;
}

void openclaw(int degrees)
{
	while(SensorValue[ClawPot] > degrees)
	{
		motor[claw] = -100;
	}
	motor[claw] = 0;
	wait1Msec(100);
}

void closeclaw(int degrees)
{
	while(SensorValue[ClawPot] < degrees)
	{
		motor[claw] = 127;
	}
	motor[claw] = -10;
	wait1Msec(100);
}

task pinch()
{
	while(activate)
	{
		motor[claw] = 127;
		wait1Msec(250);
		motor[claw] = 20;
		wait1Msec(250);
	}
}

void throw()
{
	while(SensorValue[ArmPot] > 400)
	{
		motor[leftarm] = motor[rightarm] = 127;
		if(SensorValue[ArmPot] < 1350)
		{
			if(SensorValue[ClawPot] > 2500)
			{
				motor[claw] = -127;
			}
			else
			{
				motor[claw] = 0;
			}
		}
	}
	motor[leftarm] = motor[rightarm] = -20;
	motor[claw] = 0;
}

void rightquickturn(int degrees)
{
	SensorValue[backleftIME] = 0;
	SensorValue[backrightIME] = 0;
	while(SensorValue[backrightIME] < degrees)
	{
		motor[rightdrive] = motor[rightmiddledrive] = -100;
		motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = 100;
	}
	motor[rightdrive] = motor[rightmiddledrive] = motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = 0;
	wait1Msec(100);
}

void leftquickturn(int degrees)
{
	SensorValue[backleftIME] = 0;
	SensorValue[backrightIME] = 0;
	while(SensorValue[backrightIME] < degrees)
	{
		motor[rightdrive] = motor[rightmiddledrive] = 100;
		motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = -100;
	}
	motor[rightdrive] = motor[rightmiddledrive] = motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = 0;
	wait1Msec(100);
}

task autonomous()
{
	raisearm(1900);
	motor[leftarm] = motor[rightarm] = -20;
	closeclaw(2600);
	lowerarmtobottom();
	motor[leftarm] = motor[rightarm] = -20;
	moveforward(700);
	closeclaw(3200);
	motor[claw] = 20;
	raisearm(1900);
	motor[leftarm] = motor[rightarm] = -10;
	moveforward(100);
	rightquickturn(420);
	movebackward(-800);
	throw();
	lowerarmtobottom();
	motor[leftarm] = motor[rightarm] = -20;
	openclaw(2000);
	moveforward(1150);
	closeclaw(3200);
	movebackward(-200);
	leftquickturn(-150);
	openclaw(2300);
	moveforward(200);
	closeclaw(3000);
	motor[claw] = 30;
	wait1Msec(300);
	rightquickturn(100);
	movebackward(-1130);
	throw();
	allMotorsOff();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
  	startTask(pinch);
    motor[rightdrive] = motor[rightmiddledrive] = vexRT[Ch3] - (vexRT[Ch1]/1.2);
		motor[frontleftdrive] = motor[middleleftdrive] = motor[backleftdrive] = vexRT[Ch3] + (vexRT[Ch1]/1.2);
		if(vexRT[Btn6U] == 1)
		{
			if(SensorValue[ArmPot] > 400)
			{
				motor[leftarm] = motor[rightarm] = 127;
			}
			else
			{
				motor[leftarm] = motor[rightarm] = -15;
			}
		}
		else if(vexRT[Btn6D] == 1)
		{
			if(SensorValue[bumper] == 0)
			{
				motor[leftarm] = motor[rightarm] = -127;
			}
			else
			{
				motor[leftarm] = motor[rightarm] = -20;
			}
		}
		else
		{
			motor[leftarm] = motor[rightarm] = -20;
		}
		if(vexRT[Btn5U] == 1)
		{
			if(SensorValue[ClawPot] < 3610)
			{
				motor[claw] = 127;
			}
			else
			{
				motor[claw] = 0;
			}
		}
		else if(vexRT[Btn5D] == 1)
		{
			if(SensorValue[ClawPot] > 750)
			{
				motor[claw] = -127;
			}
			else
			{
				motor[claw] = 0;
			}
		}
		else if(SensorValue[ArmPot] < 1350)
		{
			if(SensorValue[ClawPot] > 2500)
			{
				activate = false;
				motor[claw] = -127;
			}
			else
			{
				motor[claw] = 0;
			}
		}
		else
		{
			motor[claw] = 0;
		}
		if(vexRT[Btn8R])
			activate = true;
		if(vexRT[Btn8L])
			activate = false;
  }
}
