#pragma config(Sensor, in2,    ClawPot,        sensorPotentiometer)
#pragma config(Sensor, in3,    Gyro,           sensorGyro)
#pragma config(Sensor, in4,    ArmPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  bumper,         sensorTouch)
#pragma config(Sensor, dgtl2,  backrightIME,   sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  backleftIME,    sensorQuadEncoder)
#pragma config(Motor,  port2,           leftarm,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontleftdrive, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           middleleftdrive, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           backleftdrive, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           rightdrive,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightmiddledrive, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightarm,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(0)
#pragma userControlDuration(60)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

int activate = false;
/////////////////////////////////////////////////////////////////////////////////////////
//
//                         Driver Skills Template
//
// This is a template for the driver skills competition. It is identical in structure to
// the standard competition template except that the two "#pragma' statements above (and
// copied below) adjust the time limits for the competition.
//				#pragma autonomousDuration(0)
//				#pragma userControlDuration(60)
// The autonomous duration for "Driver Skills" is zero; i.e. there is no autonomous phase.
// The user control duration is 60 seconds
//
// NOTE: The above two pragmas only impact the Crystal implementation. For systems using
//       VEXNET, the VEXNET system ignores these statements as it has the durations
//       for the competition built-in.
//
// Whenever this user program is run, the duration is automatically sent to the VEX master
// processor. The master CPU will only accept these commands once per power=on cycle. So, it's
// best to power cycle your VEX to ensure that they get recognized in case you were
// previously running a standard competition program with different durations.
//
// Testing Via Crystals:
// ====================
//
// The procedure to test a Driver Skills program using the crystals is as follows:
//
// 1. Turn off power to the Crystal transmitter/joysticks.
//
// 2. Turn on your VEX so that the Driver Skills program is running.
//
// 3. Driver skills program segment of your program will start running. At the end of 60
//    seconds the VEX Master CPU will turn off the motors.
//
// 4. Repeat the above sequence
//
//
// Testing Via VEXNET Using VEXNET Competition Switch
// ==================================================
//
// The procedure to test a Driver Skills program using VEXNET Competition Switch is as follows:
//
// 1. Set the two switches on the Competition switch to "DISABLE" and "USER CONTROL"
//
// 2. Start the Driver skills program
//
// 3. Set Switch to ENABLE from DISABLE
//
// 4. You need to manually time the 60 second duration.
//
// 5. Set Switch to DISABLE
//
// 6. Repeat from step (3) to run subsequent test runs. There's no need to reset the VEX or
//    restart your user program.
//
//
// Testing Via VEXNET Using ROBOTC IDE
// ==================================================
//
// It is not necessary to own a VEXNET switch. ROBOTC has a test window that allows the same functionality.
// The test window has three buttons for "DISABLE", "AUTONOMOUS", "USER CONTROL".
//
// 1. Open the ROBOTC Debugger. Then open the "Competition Control" Debugger window.
//
// 2. Start your Driver Skills program running.
//
// 3. Click the "DISABLED" button on the "Competition Control" window.
//
// 4. Click the "USER CONTROL" button on the "Competition Control" window.
//
// 5. You need to manually time the 60 second duration.
//
// 6. Click the "DISABLED" button on the "Competition Control" window.
//
// 7. Repeat from step (4) to run subsequent test runs. There's no need to reset the VEX or
//    restart your user program.
//
/////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
void turnright(int degrees10)
{
	SensorValue[Gyro] = 0;
	int error = 5;

	//While the absolute value of the gyro is less than the desired rotation - 100...
	while(abs(SensorValue[in3]) < degrees10 - 100)
	{
		motor[rightdrive] = motor[rightmiddledrive] = -75;
		motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = 75;
	}
	//Brief brake to eliminate some drift
	motor[rightdrive] = motor[rightmiddledrive] = 5;
	motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = -5;
	wait1Msec(100);

	//Second while loop to move the robot more slowly to its goal, also setting up a range
	//for the amount of acceptable error in the system
	while(abs(SensorValue[in3]) > degrees10 + error || abs(SensorValue[in3]) < degrees10 - error)
	{
		if(abs(SensorValue[in3]) > degrees10)
		{
			motor[rightdrive] = motor[rightmiddledrive] = 30;
			motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = -30;
		}
		else
		{
			motor[rightdrive] = motor[rightmiddledrive] = -30;
			motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = 30;
		}
	}
	//Stop
	motor[rightdrive] = motor[rightmiddledrive] = 0;
	motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = 0;
	wait1Msec(250);
}

void turnleft(int degrees10)
{
	SensorValue[Gyro] = 0;
	int error = 5;

	//While the absolute value of the gyro is less than the desired rotation - 100...
	while(abs(SensorValue[in3]) < degrees10 - 100)
	{
		motor[rightdrive] = motor[rightmiddledrive] = 75;
		motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = -75;
	}
	//Brief brake to eliminate some drift
	motor[rightdrive] = motor[rightmiddledrive] = -5;
	motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = 5;
	wait1Msec(100);

	//Second while loop to move the robot more slowly to its goal, also setting up a range
	//for the amount of acceptable error in the system
	while(abs(SensorValue[in3]) > degrees10 + error || abs(SensorValue[in3]) < degrees10 - error)
	{
		if(abs(SensorValue[in3]) > degrees10)
		{
			motor[rightdrive] = motor[rightmiddledrive] = -30;
			motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = 30;
		}
		else
		{
			motor[rightdrive] = motor[rightmiddledrive] = 30;
			motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = -30;
		}
	}
	//Stop
	motor[rightdrive] = motor[rightmiddledrive] = 0;
	motor[frontleftdrive] = motor[backleftdrive] = motor[middleleftdrive] = 0;
	wait1Msec(250);
}

void moveforward(int degrees)
{
	SensorValue[backleftIME] = 0;
	SensorValue[backrightIME] = 0;
	while(SensorValue[backleftIME] < degrees)
	{
		motor[rightdrive] = motor[rightmiddledrive] = motor[frontleftdrive] = motor[middleleftdrive] = motor[backleftdrive] = 127;
	}
	motor[rightdrive] = motor[rightmiddledrive] = motor[frontleftdrive] = motor[middleleftdrive] = motor[backleftdrive] = 0;
	wait1Msec(100);
}

void movebackward(int degrees)
{
	SensorValue[backleftIME] = 0;
	SensorValue[backrightIME] = 0;
	while(SensorValue[backleftIME] > degrees)
	{
		motor[rightdrive] = motor[rightmiddledrive] = motor[frontleftdrive] = motor[middleleftdrive] = motor[backleftdrive] = -75;
	}
	motor[rightdrive] = motor[rightmiddledrive] = motor[frontleftdrive] = motor[middleleftdrive] = motor[backleftdrive] = 0;
	wait1Msec(100);
}

void raisearm(int degrees)
{
	while(SensorValue[ArmPot] > degrees)
	{
		motor[rightarm] = motor[leftarm] = 40;
	}
	motor[leftarm] = motor[rightarm] = -20;
}

void lowerarm(int degrees)
{
	while(SensorValue[ArmPot] < degrees)
	{
		motor[leftarm] = motor[rightarm] = -70;
	}
	motor[leftarm] = motor[rightarm] = 0;
}

void lowerarmtobottom()
{
	while(SensorValue[bumper] == 0)
	{
		motor[leftarm] = motor[rightarm] = -70;
	}
	motor[leftarm] = motor[rightarm] = -20;
}

void openclaw(int degrees)
{
	while(SensorValue[ClawPot] > degrees)
	{
		motor[claw] = -100;
	}
	motor[claw] = 0;
	wait1Msec(100);
}

void closeclaw(int degrees)
{
	while(SensorValue[ClawPot] < degrees)
	{
		motor[claw] = 127;
	}
	motor[claw] = -10;
	wait1Msec(100);
}

task pinch()
{
	while(activate)
	{
		motor[claw] = 127;
		wait1Msec(250);
		motor[claw] = 20;
		wait1Msec(250);
	}
}

void throw()
{
	while(SensorValue[ArmPot] > 400)
	{
		motor[leftarm] = motor[rightarm] = 127;
		if(SensorValue[ArmPot] < 1350)
		{
			if(SensorValue[ClawPot] > 2500)
			{
				motor[claw] = -127;
			}
			else
			{
				motor[claw] = 0;
			}
		}
	}
	motor[leftarm] = motor[rightarm] = -20;
	motor[claw] = 0;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// The "Driver Skills" competition has no autonomous phase. Simply leave the following
// placeholder.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	movebackward(-300);
	raisearm(2000);
	motor[leftarm] = motor[rightarm] = -20;
	closeclaw(2000);
	lowerarmtobottom();
	motor[leftarm] = motor[rightarm] = -20;
	moveforward(100);
	wait1Msec(250);
	closeclaw(3000);
	motor[claw] = 40;
	wait1Msec(200);
	movebackward(-100);
	raisearm(2500);
	motor[rightarm] = motor[leftarm] = -10;
	movebackward(-1150);
	throw();			//first preload throw//
	lowerarmtobottom();
	moveforward(750);
	closeclaw(3100);
	motor[claw] = 20;
	wait1Msec(200);
	movebackward(-100);
	raisearm(2500);
	motor[rightarm] = motor[leftarm] = -10;
	movebackward(-900);
	throw();			//second preload throw//
	lowerarmtobottom();
	moveforward(900);
	closeclaw(3100);
	motor[claw] = 20;
	wait1Msec(200);
	movebackward(-100);
	raisearm(2500);
	motor[rightarm] = motor[leftarm] = -10;
	movebackward(-820);
	throw();			//third preload throw//
	lowerarmtobottom();
	motor[rightarm] = motor[leftarm] = -20;
	raisearm(2200);
	motor[rightarm] = motor[leftarm] = -20;
	turnright(975);
	lowerarmtobottom();
	motor[rightarm] = motor[leftarm] = -20;
	moveforward(150);
	closeclaw(3500);
	turnleft(900);
	moveforward(800);
	openclaw(2500);
	moveforward(200);
	closeclaw(3400);
	motor[claw] = 20;
	movebackward(-100);
	raisearm(2000);
	motor[rightarm] = motor[leftarm] = -10;
	turnleft(100);
	movebackward(-1000);
	throw();                 //throw both nearest side stars//
	//motor[leftarm] = motor[rightarm] = -20;
	//lowerarmtobottom();
	//openclaw(1300);
	//turnleft(975);
	//moveforward(1500);
	//closeclaw(1500);
	//motor[claw] = 20;
	//raisearm(2000);
	//turnright(975);
	//throw();                 //throw inner mid stars//
	//motor[leftarm] = motor[rightarm] = -20;
	//lowerarmtobottom();
	//openclaw(1300);
	//moveforward(650);
	//closeclaw(1500);
	//motor[claw] = 20;
	//raisearm(2000);
	//movebackward(650);
	//throw();			//throw mid cube//
	//motor[leftarm] = motor[rightarm] = -20;
	//lowerarmtobottom();
	//openclaw(1300);
	//moveforward(1000);
	//closeclaw(1500);
	//motor[claw] = 20;
	//raisearm(2000);
	//movebackward(1000);
	//throw();			//throw outter mid stars//
	//motor[leftarm] = motor[rightarm] = -20;
	//lowerarmtobottom();
	//openclaw(1300);
	//moveforward(1000);
	//turnleft(975);
	//moveforward(400);
	//closeclaw(1500);
	//motor[claw] = 20;
	//raisearm(2000);
	//turnright(975);
	//movebackward(1000);
	//throw();                 //throw last cube remaining//
	//motor[leftarm] = motor[rightarm] = -20;
	//lowerarmtobottom();
	//openclaw(1300);
	//turnleft(975);
	//moveforward(600);
	//turnright(975);
	//moveforward(1200);
	//closeclaw(1500);
	//motor[claw] = 20;
	//raisearm(2000);
	//movebackward(1200);
	//throw();			//throw last side stars//

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

  while (true)
  {
  	startTask(pinch);
    motor[rightdrive] = motor[rightmiddledrive] = vexRT[Ch3] - (vexRT[Ch1]/1.2);
		motor[frontleftdrive] = motor[middleleftdrive] = motor[backleftdrive] = vexRT[Ch3] + (vexRT[Ch1]/1.2);
		if(vexRT[Btn6U] == 1)
		{
			if(SensorValue[ArmPot] > 400)
			{
				motor[leftarm] = motor[rightarm] = 127;
			}
			else
			{
				motor[leftarm] = motor[rightarm] = -15;
			}
		}
		else if(vexRT[Btn6D] == 1)
		{
			if(SensorValue[bumper] == 0)
			{
				motor[leftarm] = motor[rightarm] = -127;
			}
			else
			{
				motor[leftarm] = motor[rightarm] = -20;
			}
		}
		else
		{
			motor[leftarm] = motor[rightarm] = -20;
		}
		if(vexRT[Btn5U] == 1)
		{
			if(SensorValue[ClawPot] < 3610)
			{
				motor[claw] = 127;
			}
			else
			{
				motor[claw] = 0;
			}
		}
		else if(vexRT[Btn5D] == 1)
		{
			if(SensorValue[ClawPot] > 750)
			{
				motor[claw] = -127;
			}
			else
			{
				motor[claw] = 0;
			}
		}
		else if(SensorValue[ArmPot] < 1350)
		{
			if(SensorValue[ClawPot] > 2500)
			{
				activate = false;
				motor[claw] = -127;
			}
			else
			{
				motor[claw] = 0;
			}
		}
		else
		{
			motor[claw] = 0;
		}
		if(vexRT[Btn8R])
			activate = true;
		if(vexRT[Btn8L])
			activate = false;
  }
}
